[[redirects]]
  from = "/dA/*"
  to = "https://demo.dotcms.com/dA/:splat"
  status = 200
  force = true

 [[redirects]]
  from = "/api/*"
  to = "https://demo.dotcms.com/api/:splat"
  status = 200
  force = true

 [[redirects]]
  from = "/application/*"
  to = "https://demo.dotcms.com/application/:splat"
  status = 200
  force = true


 [[redirects]]
  from = "/custom-elements/*"
  to = "https://demo.dotcms.com/custom-elements/:splat"
  status = 200
  force = true